apiVersion: batch/v1
kind: Job
metadata:
  name: rekey-tang
  namespace: openshift-machine-config-operator
spec:
  template:
    metadata:
      labels:
        name: rekey-tang
    spec:
      containers:
      - name: rekey-tang
        image: quay.io/centos/centos:8
        imagePullPolicy: IfNotPresent
        command:
        - "/sbin/chroot"
        - "/host"
        - "/bin/bash"
        - "-ec"
        args:
        - |
          echo "Current tang pin:"
          clevis-luks-list -d /dev/sda4 -s 1
          echo "Applying new tang pin: $NEW_TANG_PIN"
          clevis-luks-edit -f -d /dev/sda4 -s 1 -c "$NEW_TANG_PIN"
          echo "Pin applied successfully"
        env:
        - name: NEW_TANG_PIN
          value: >-
            {"t":1,"pins":{"tang":[
              {"url":"http://tangserver02:7500","thp":"tang-thumbprint-2"},
              {"url":"http://tangserver01:7500","thp":"tang-thumbprint-1"},
              {"url":"http://tangserver03:7500","thp":"tang-thumbprint-3"}
            ]}}
        volumeMounts:
        - name: hostroot
          mountPath: /host
        securityContext:
          privileged: true
      volumes:
      - name: hostroot
        hostPath:
          path: /
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Never
      serviceAccount: machine-config-daemon
      serviceAccountName: machine-config-daemon
